### ISSUE TITLE
Concurrency not supported

### ISSUE THREAD

**Issue by etatus** [danimtb/dasshio#58] opened 2018-09-20 17:03 UTC
If you have 2 dash buttons and press both at the same time ( I guess within the timeout configured in config.json), it is only detected one of them.

Version 0.3.1

Related to: https://github.com/danimtb/dasshio/issues/34

**Comment by danimtb** [comment] 2019-04-14 15:41
This should be fixed once #34 is implemented

**Comment by danimtb** [comment] 2019-11-15 21:44
Closing this as a duplicate of #34. Thanks!

**Closed as completed by danimtb** 2019-11-15 21:44 UTC
