### ISSUE TITLE
Dasshio add-on not running

### ISSUE THREAD

**Issue by wshankles** [danimtb/dasshio#40] opened 2018-07-12 21:01 UTC
The add-on does not auto start and when manually starting it does not indicate it has started from the dashboard (puzzle piece is grey).  Nothing is shown in the dasshio log.

**Comment by dancormier** [comment] 2018-07-14 18:57
Also being documented here: https://community.home-assistant.io/t/dasshio-amazon-dash-buttons-hass-io-add-on/25027/56

**Comment by M1ch43LN** [comment] 2018-07-14 19:03
Thanks

**Comment by chuchyeltronco** [comment] 2018-07-15 14:25
Hello, yesterday I Installed Dasshio, On My Hass.io Version 115 with System Resin OS 2.3.0+rev1 and Home Assistant 0.73.1, But The Problem Is Dasshio Never Start. Please If You can check for This Problem, Thks In Advance.

**Comment by wshankles** [comment] 2018-07-15 14:58
@chuchyeltronco the developer know's about the problem and will be working on it soon.

**Comment by danimtb** [comment] 2018-07-18 16:08
Just release 0.3.0 with some improvements. Should work in HassOS and ResinOS. Please try and let me know.

**Comment by Erreon** [comment] 2018-07-18 19:45
I've updated and when I try to click start I see:
2018-07-18 14:44:24 ERROR (MainThread) [homeassistant.components.websocket_api] WS 1880581712: Received invalid command: auth/current_user

**Comment by maramazza** [comment] 2018-07-19 09:29
Information:
Hardware: 
- Raspberry Pi 3 Modello B

Software: 
- Hass.io supervisor Version: 115
- System	Resin OS 2.3.0+rev1
- Dasshio 0.3.0

All the time that i try to start the component i have this error

"18-07-19 09:25:51 ERROR (SyncWorker_6) [hassio.docker] Can't create container from addon_03d23610_dasshio: 404 Client Error: Not Found ("No such image: danimtb/armhf-dasshio:latest")"

**Comment by danimtb** [comment] 2018-07-19 09:51
Could you try uninstalling, removing the repository from the add-on store and reinstall everything again?

**Comment by Erreon** [comment] 2018-07-19 13:29
@danimtb that worked for me! I dunno why I didn't try that before. I did it a million times before this issue was reported. Thanks!

**Comment by danimtb** [comment] 2018-07-19 14:55
Please give it a try to the steps indicated above @wshankles @mn26826 @chuchyeltronco @maramazza and please report back with the OS and versions if any issue.

**Comment by maur54** [comment] 2018-07-19 15:21
Also my dashbotton stopped from today

uninstalled dasshio and reinstalled ----->> now goes!!

Home Assistant
0.73.2

Hass.io supervisor
Version	115
Latest version	115

Host system
Hostname	hassio
System	Resin OS 2.3.0+rev1

Raspberry Pi 3 Modello B

**Comment by maramazza** [comment] 2018-07-20 06:24
> Please give it a try to the steps indicated above @wshankles @mn26826 @chuchyeltronco @maramazza and please report back with the OS and versions if any issue.

@danimtb For me now is perfect! Thanks!

**Comment by adonno** [comment] 2018-07-21 15:04
@danimtb tried runng the addon on my hassos sytem but it isn't starting i added the repository this morning and installed the addon / reide uninstalling and reinstalling but no success 

did i miss smth in the config ?  

```
{
  "timeout": 20,
  "buttons": [
    {
      "name": "oralb",
      "address": "ma:ca:dd:re:ss:ss",
      "domain": "light",
      "service": "toggle",
      "service_data": "{\"entity_id\": \"light.mirroir_parents\"}"
    }
  ]
}
```

**Comment by RyanRayNeff** [comment] 2018-07-21 16:18
@danimtb removing everything and reinstalling worked for me. Thanks!

**Comment by chuchyeltronco** [comment] 2018-07-22 18:35
I remove every things and reinstall and now working, thks

**Comment by adonno** [comment] 2018-07-24 16:32
now i'm getting : 

Can't start addon_03d23610_dasshio: 500 Server Error: Internal Server Error ("structure needs cleaning: unknown")

**Comment by adonno** [comment] 2018-07-24 17:18
got it working after saving the changes and restarting hassio

**Comment by danimtb** [comment] 2018-07-24 21:21
Thanks for the comments. Closing this. Please open a new issue in case you have this problem again

**Closed as completed by danimtb** 2018-07-24 21:21 UTC
