### ISSUE TITLE
Dashio crashing itself

### ISSUE THREAD

**Issue by cryptooth** [danimtb/dasshio#61] opened 2018-10-31 15:19 UTC
I just moved HASSIO (RP3) to UBUNTU 16.04 (VM).

Dashio v0.3.1

All dependicies installed and all add-on works perfectly. But Dashio keeps crashing sometimes. Here is the error log:

```
`2018-10-31 14:26:03,323 | INFO | Reading config file: /data/options.json
2018-10-31 14:26:03,324 | INFO | Starting sniffing...
Traceback (most recent call last):
  File "/dasshio.py", line 27, in arp_display
    mac = pkt[ARP].hwsrc.lower()
  File "/usr/lib/python3.6/site-packages/scapy/packet.py", line 966, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [ARP] not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dasshio.py", line 149, in <module>
    count=0)
  File "/usr/lib/python3.6/site-packages/scapy/sendrecv.py", line 783, in sniff
    if stop_filter and stop_filter(p):
  File "/dasshio.py", line 29, in arp_display
    mac = pkt[Ether].src.lower()
  File "/usr/lib/python3.6/site-packages/scapy/packet.py", line 966, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [Ether] not found`
```

Any advice?

**Comment by danimtb** [comment] 2018-10-31 15:33
Does this happen after pressing one button?

I am currently runing hassio on an Ubuntu 18 machine without issues. Maybe this is a problem of the network sniffing filter here: https://github.com/danimtb/dasshio/blob/70a696fdadac41340d92df5626214bcdf1d75aa4/dasshio/dasshio.py#L147

**Comment by danimtb** [comment] 2018-10-31 15:44
Just realized this is a duplicate of #44 
Please follow the conversation there!

**Closed as completed** 2018-10-31 15:45 UTC

**Comment by cryptooth** [comment] 2018-10-31 16:19
Yes. When I pressed the button, add-on crashes.



 <>
