### ISSUE TITLE
Huge Dasshio File in Hass.io

### ISSUE THREAD

**Issue by anndrewww** [danimtb/dasshio#20] opened 2017-12-05 02:41 UTC
In my quest to find the cause of otherwise random hangs in the Frontend/SSH/Samba where my automations etc continue despite needing to power cycle my Pi3, I have noticed that the Dasshio segment of my snapshots often grows into excess of 70-80MB. Is this normal?

**Comment by danimtb** [comment] 2017-12-10 22:21
Hi @anndrewww and thank you so much for reporting.

I have seen other users of Dasshio reporting this same issue and I would like to know the steps to reproduce it. I have done some snapshots of my hass.io instance but I can't see the compressed file of Dasshio.

I am not sure if 3rd party are packed inside the snapshot. Could you please clarify me this?

**Comment by anndrewww** [comment] 2017-12-12 05:20
3rd party add-ons are in the Snapshots.

The Dasshio file is 66.4MB of the 72MB Snapshot file. The Dasshio backup file, "0XXXXX0_dasshio.tar.gz", contains a file "image.tar" - 169.2MB, which contains numerous folders, each containing a "layer.tar" file, one such "layer.tar" files is 142MB.

To replicate, I created a Snapshot after setting up at least one (1) Dash device and using it. Expanded the files contained within the Dasshio file of the Snapshot and located numerous "layer.tar" files of significant size, 5MB - 142MB.

**Comment by danimtb** [comment] 2017-12-16 17:16
Dont know why my Dasshio config is not saved inside the snapshot...

btw, what's the content of those `layer.tar` files?

**Comment by namadori** [comment] 2018-01-20 10:14
I made a snapshot on Hassio 0.83 (HA 0.61.1) and it doesn't contain anything about Dasshio. Other plugins are backed up with meaningful names, Node-red is archived as "share.tar.gz".
@danimtb I can make some tests if you need it.

**Comment by danimtb** [comment] 2018-02-21 10:27
Hi @namadori!

I think Dasshio (and other 3rd-party addons) should be packed inside the snapshot... Is not the default behaviour?

Could you do some test from your side please? I need double checking this.
Many thanks!

**Comment by namadori** [comment] 2018-02-22 13:41
Latest backup with 0.63 contains dasshio (03d23610_dasshio.tar.gz, 65MB). Also Node Red backup become huge (248MB) and snapshot time got up between 4 to 6 hours.

**Comment by danimtb** [comment] 2018-03-04 19:35
Hi. I have recently made a snapshot and the size of it is because of the image for this addon is built inside your raspberry pi, so the snapshot saves the config as well as the image.

This is the default behavior and is working as expected so I guess we can close the issue for now.

Please @anndrewww, report back or reopen this issue in case you still fin trouble. Thanks!

**Closed as completed by danimtb** 2018-03-04 19:35 UTC
Labels: help wanted, question
